### ISSUE TITLE
Can't build : missing file(s)

### ISSUE THREAD

**Issue by dbaelde** [DrStrangelove42/DreamOfaRidiculousMan#1]
I get the following error when trying to build at cf3bcd24b8f2e6fa4dc500c4501f8dacfe3388ee:
```
Source/Maps/../Blocks/../Characters/Player.h:9:10: fatal error: ../Items/item.h: No such file or directory
 #include "../Items/item.h"
          ^~~~~~~~~~~~~~~~~
```
Can you fix and make sure there is no other problem of this sort ? You can also manually check by building from a fresh clone, but the continuous integration should do it (have done it) automatically.

**Comment by DrStrangelove42** [comment]
I just ‘make clean’ and ‘make all’ again it seems to be compiling well for me(macOS), and I checked the file is there, that seems weird, I’ll wait for others to check with Linux !

**Comment by DrStrangelove42** [comment]
It was a typo for ‘items.h’ should be ‘Items.h’, just fixed!

**Comment by ads5699** [comment]
It should be working now, it seems that our compilers circumnavigated this problem.
Sorry for the late return!
